### ISSUE TITLE
Improve "ceil" function by adding a "rounding" decimals parameter

### ISSUE THREAD

**Issue by alexgarciab** [mbaersch/number-string-operations#2]
Would it be possible to improve the "ceil" function adding an extra parameter which would be "rounding" decimals.

So for example, if the input is 42.6 and the rounding is 2, then the output would be 42.60.

If the input is 42.6 and the rounding is 0, then the output would be 43.

And the same for a long number. If the input is 42.6739123 and the rounding is 2, then the output would be 42.67.

Is this something you can implement in the sGTM variable?

**Comment by mbaersch** [comment]
the short answer is "no". Because it is just a call to an existing function: the sandboxed version of *ceil* and this function has a clearly defined purpose and accepts only one parameter (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil). 

What you are looking for seems to be a function that formats a number by rounding with a fixed number of decimals. So would not be "toFixed" the (already existing) right option for that?

![image](https://github.com/mbaersch/number-string-operations/assets/15323700/d9e83b6e-cd7f-4e54-bbee-8bf390606336)

**Comment by alexgarciab** [comment]
Ok, I see. It would be useful if you can add ALL the functions to the Examples tables in the README so that it is clear what the GTM variable can do (including the toFixed function).

**Comment by mbaersch** [comment]
> Ok, I see. It would be useful if you can add ALL the functions to the Examples tables in the README so that it is clear what the GTM variable can do (including the toFixed function).

feel free to contribute a complete list as a comment and I will update the readme file. All functions are based on existing JS functions with the same name

**Comment by alexgarciab** [comment]
@mbaersch here's the updated README info table with all the functions from the template code:

## Examples

Type | Operation / Function | Parameter 1 | Parameter 2 | Parameter 3 | JavaScript Equivalent | Result
---- | ---- | ---- | ---- | ---- | ---- | ----
Calculate | add | 2 | 5.5 | -unused- | 2 + 5.5 | 7.5
Calculate | subtract | 5.5 | 2 | -unused- | 5.5 - 2 | 3.5
Calculate | multiply | 2 | 5.5 | -unused- | 2 * 5.5 | 11
Calculate | divide | 10 | 2 | -unused- | 10 / 2 | 5
Math Methods | abs | -42.6 | -unused- | -unused- | Math.abs(-42.6) | 42.6
Math Methods | ceil | 42.6 | -unused- | -unused- | Math.ceil(42.6) | 43
Math Methods | floor | 42.6 | -unused- | -unused- | Math.floor(42.6) | 42
Math Methods | max | 42.6 | 50 | -unused- | Math.max(42.6, 50) | 50
Math Methods | min | 42.6 | 2 | -unused- | Math.min(42.6, 2) | 2
Math Methods | round | 42.6 | -unused- | -unused- | Math.round(42.6) | 43
Math Methods | trunc | 42.6 | -unused- | -unused- | Math.floor(42.6) | 42
Math Methods | pow | 2 | 3 | -unused- | Math.pow(2, 3) | 8
Math Methods | sqrt | 9 | -unused- | -unused- | Math.sqrt(9) | 3
String Functions | indexOf | Frodo | o | -unused- | "Frodo".indexOf('o') | 2
String Functions | lastIndexOf | Frodo | o | -unused- | "Frodo".lastIndexOf('o') | 4
String Functions | split | first,second,third | , | -unused- | "first,second,third".split(',') | ["first", "second", "third"]
String Functions | splitSpecial | first,second,third | , | 1 | "first,second,third".split(',')[1] | "second"
String Functions | toLowerCase | Frodo | -unused- | -unused- | "Frodo".toLowerCase() | "frodo"
String Functions | toUpperCase | Frodo | -unused- | -unused- | "Frodo".toUpperCase() | "FRODO"
String Functions | replace | Frodo | o | a | "Frodo".replace('o', 'a') | "Frado"
String Functions | replaceAll | Frodo | o | a | replaceAll("Frodo", 'o', 'a') | "Frada"
String Functions | slice | Frodo | 1 | 3 | "Frodo".slice(1, 3) | "ro"
String Functions | substr | Frodo | 2 | 3 | "Frodo".substring(2, 5) | "odo"
String Functions | substring | Frodo | 2 | 3 | "Frodo".substring(2, 3) | "o"
String Functions | toFixed | 3.14159 | 2 | -unused- | (3.14159).toFixed(2) | 3.14
String Functions | toNumber | 1,234.56 | -unused- | -unused- | +(1,234.56) | 1234.56
String Functions | match | Frodo | /o/ | -unused- | "Frodo".match(/o/) | ["o"]
String Functions | sha256 | Hello, World! | -unused- | -unused- | sha256Sync("Hello, World!") | "dffd6021bb2bd5b0af676290809ec3a53191dd81c7f70a4b28688a362182986f"
String Functions | base64 | Hello, World! | -unused- | -unused- | toBase64("Hello, World!") | "SGVsbG8sIFdvcmxkIQ=="
String Functions | jstringify | {name: "Frodo", age: 50} | -unused- | -unused- | JSON.stringify({name: "Frodo", age: 50}) | '{"name":"Frodo","age":50}'
String Functions | jparse | '{"name":"Frodo","age":50}' | -unused- | -unused- | JSON.parse('{"name":"Frodo","age":50}') | {name: "Frodo", age: 50}

**Comment by mbaersch** [comment]
awesome, thanks! README already updated.
